Login, register fix
mehmedkadric/a-movie-database pull request #2
Opened 2022-12-31 19:48 UTC by kosharun

In the navbar "Login", "Register" or "Logout" buttons are now right-aligned. 
Login and Register forms are now supported with bootstrap and they look cool.
Superuser is created with username: admin and password: admin. (also we can now make accounts)
Everything that was in the "core" app that was related to users is moved to the app "accounts".

2022-12-31 21:03 UTC, mehmedkadric requested changes

2022-12-31 21:03 UTC, mehmedkadric commented on aMovieDatabase/accounts/templates/register.html
> +        <button type="submit" class="btn btn-primary btn-block">Register</button>
When you press the button, did you check if user is created? Did you try to login?

2022-12-31 21:19 UTC, kosharun commented on aMovieDatabase/accounts/forms.py
> +        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
Should I add them when I find them?

2022-12-31 21:24 UTC, kosharun commented on aMovieDatabase/accounts/templates/register.html
> +        <button type="submit" class="btn btn-primary btn-block">Register</button>
User is created, and when we press "Register" it automatically logs us in but in the Login option on the navbar, logging in doesn't work because we still haven't made a class in views.py for logging in.

2022-12-31 21:50 UTC, mehmedkadric commented on aMovieDatabase/accounts/forms.py
> +        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
I would say so. Investigate The topic of recommender systems (maybe ML-based). Check for standard model inputs.

2022-12-31 21:51 UTC, mehmedkadric commented on aMovieDatabase/accounts/templates/register.html
> +        <button type="submit" class="btn btn-primary btn-block">Register</button>
Maybe we should add that as well?

2023-01-01 09:15 UTC, mehmedkadric commented on aMovieDatabase/accounts/templates/register.html
> +        <button type="submit" class="btn btn-primary btn-block">Register</button>
We should add some more features here. Username should be displayed in navbar after login. An info message should be popped up after login/register/logout action. If some of those actions are not possible, display what's wrong (e.g. password should have more than 4 characters).

2023-01-02 13:26 UTC, kosharun commented on aMovieDatabase/accounts/forms.py
> +        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
Fields: "date of birth" and "3 favorite genres" are added

2023-01-02 13:27 UTC, kosharun commented on aMovieDatabase/accounts/templates/register.html
> +        <button type="submit" class="btn btn-primary btn-block">Register</button>
Username is displayed on the navbar after login.

2023-01-02 18:46 UTC, closed without merging