Enhance movies scoring logic
mehmedkadric/a-movie-database pull request #43
Opened 2023-01-23 20:52 UTC by ahmedjasarevic

Now top 3 movies are scored by vote average and popularity

2023-01-26 12:02 UTC, mehmedkadric requested changes

2023-01-26 12:02 UTC, mehmedkadric commented on aMovieDatabase/movies/views.py
> +            'topMovies' : top_movies,
Sometimes you use camelCase notation and sometimes under_score. Choose one (maybe under_score is good option for Python/Django).

2023-01-26 17:53 UTC, ahmedjasarevic commented on aMovieDatabase/movies/views.py
> +            'topMovies' : top_movies,
Okay. I will use under_score option.

2023-01-30 12:37 UTC, mehmedkadric approved these changes

2023-01-30 13:33 UTC, merged